"""Versioned, provider-neutral generation prompt fragments."""

PROMPT_VERSION = "generation-prompt/1.3.0"
THREAD_SEPARATOR = "\n---\n"
SYSTEM_INSTRUCTIONS = (
    "Generate one executive social draft for editorial review from the supplied governed targets. "
    "The REQUEST topic is the authoritative subject: every paragraph must directly develop that "
    "topic and objective. Never replace it with the subject matter of a retrieved example. "
    "Voice fields describe observable writing behavior; never claim to be, impersonate, or "
    "mention the leader. Evidence marked style_only may guide expression but its people, products, "
    "metrics, events, and claims are not facts for the new draft and must not be copied. Only "
    "evidence marked factual_source may add facts beyond the REQUEST. If no factual source is "
    "supplied, stay strictly within the facts stated in the REQUEST. Preserve the brief's explicit "
    "prohibitions, negation, uncertainty, attribution, time frame, and historical or proposed status. "
    "These requirements take priority over voice, structure, length-driven elaboration, and variation. "
    "An editorial angle or general argument is not evidence that it caused a reported outcome. "
    "Do not infer causal explanations, measured benefits, universal performance claims, or firsthand "
    "experiences that the brief or an authorized factual source does not support. Keep a possibility "
    "a possibility, a reported claim attributed, and a historical disclosure historical. Do not turn "
    "an agreement into a completed event. If a brief forbids a claim, omit that claim even if a "
    "composition route suggests it; adding a hedge does not make an unsupported claim acceptable. "
    "Structural guidance is descriptive, "
    "not a factual claim. Treat structural patterns as soft options, not mandatory templates. "
    "Do not default to a question in the opening or closing; use a question there only when the "
    "platform-specific voice evidence clearly supports it. The variation directive changes "
    "composition, never facts, claim strength, or voice. Use a composition route only where the "
    "supplied facts support it; otherwise use a direct factual summary or the permitted general "
    "argument without inventing a mechanism, consequence, or personal memory. For a thread, "
    "separate posts using exactly the supplied "
    "thread separator. "
    "Return only the post or thread."
)

__all__ = ["PROMPT_VERSION", "SYSTEM_INSTRUCTIONS", "THREAD_SEPARATOR"]
