"""Heterogeneous source ingestion contracts and pipeline boundaries."""

from ceo_voice.ingestion.connectors import (
    ConnectorRegistry,
    ExportRecord,
    LocalExportConnector,
    SourceConnector,
)
from ceo_voice.ingestion.contracts import (
    CleanDocument,
    CleanedContent,
    ConnectorCapabilities,
    ConnectorCheckpoint,
    ExtractedMetadata,
    FetchRequest,
    IngestionDocument,
    ParsedContent,
    RawDocument,
    SourceItem,
)
from ceo_voice.ingestion.incremental import IncrementalPlanner
from ceo_voice.ingestion.outcomes import (
    DocumentChangeDecision,
    DocumentChangeKind,
    IngestionItemResult,
    IngestionItemStatus,
    IngestionRunResult,
    IngestionRunStatus,
    RepositoryWriteDisposition,
    ValidationIssue,
    ValidationResult,
    ValidationSeverity,
)
from ceo_voice.ingestion.pipeline import IngestionPipeline
from ceo_voice.ingestion.repositories import (
    CheckpointRepository,
    CleanDocumentRepository,
    IngestionRepositories,
    InMemoryCheckpointRepository,
    InMemoryCleanDocumentRepository,
    InMemoryMetadataRepository,
    InMemoryRawDocumentRepository,
    MetadataRepository,
    RawDocumentRepository,
    to_clean_document,
)
from ceo_voice.ingestion.stages import (
    ContentParser,
    DocumentCleaner,
    DocumentNormalizer,
    DocumentValidator,
    MetadataExtractor,
    RawDocumentFactory,
    SourceItemValidator,
)

__all__ = [
    "CheckpointRepository",
    "CleanDocument",
    "CleanDocumentRepository",
    "CleanedContent",
    "ConnectorCapabilities",
    "ConnectorCheckpoint",
    "ConnectorRegistry",
    "ContentParser",
    "DocumentChangeDecision",
    "DocumentChangeKind",
    "DocumentCleaner",
    "DocumentNormalizer",
    "DocumentValidator",
    "ExportRecord",
    "ExtractedMetadata",
    "FetchRequest",
    "InMemoryCheckpointRepository",
    "InMemoryCleanDocumentRepository",
    "InMemoryMetadataRepository",
    "InMemoryRawDocumentRepository",
    "IncrementalPlanner",
    "IngestionDocument",
    "IngestionItemResult",
    "IngestionItemStatus",
    "IngestionPipeline",
    "IngestionRepositories",
    "IngestionRunResult",
    "IngestionRunStatus",
    "LocalExportConnector",
    "MetadataExtractor",
    "MetadataRepository",
    "ParsedContent",
    "RawDocument",
    "RawDocumentFactory",
    "RawDocumentRepository",
    "RepositoryWriteDisposition",
    "SourceConnector",
    "SourceItem",
    "SourceItemValidator",
    "ValidationIssue",
    "ValidationResult",
    "ValidationSeverity",
    "to_clean_document",
]
